apiVersion: apps/v1
kind: Deployment
metadata:
  name: basket-api
  labels:
    app: basket-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: basket-api
  template:
    metadata:
      labels:
        app: basket-api
    spec:
      containers:
      - name: basket-api
        image: basket-api:v1
        ports:
        - containerPort: 80
