apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhooks-api
  labels:
    app: webhooks-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webhooks-api
  template:
    metadata:
      labels:
        app: webhooks-api
    spec:
      containers:
      - name: webhooks-api
        image: webhooks-api:v1
        ports:
        - containerPort: 80
